In [28]:
import os
import hashlib

def get_file_hash(filename):
    # Create a hash of the file's content
    hasher = hashlib.md5()
    with open(filename, "rb") as f:
        while True:
            data = f.read(65536)  # Read in 64k chunks
            if not data:
                break
            hasher.update(data)
    return hasher.hexdigest()

def find_duplicate_images(directory):
    # Create a dictionary to store image hashes and their corresponding file paths
    hash_dict = {}
    duplicate_images = []

    for root, _, files in os.walk(directory):
        for file in files:
            # Check if the file is an image (you can add more image extensions as needed)
            if file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                file_path = os.path.join(root, file)
                file_hash = get_file_hash(file_path)

                # If a file with the same hash is already in the dictionary, it's a duplicate
                if file_hash in hash_dict:
                    duplicate_images.append((file_path, hash_dict[file_hash]))
                else:
                    hash_dict[file_hash] = file_path

    return duplicate_images

# Specify the directory containing your image dataset
image_directory = "C:\\Users\\rawat\\Downloads\\MangoLeafBD Dataset"

duplicate_images = find_duplicate_images(image_directory)

if duplicate_images:
    print("Duplicate Images:")
    for index, (image1, image2) in enumerate(duplicate_images):
        print(f"Duplicate pair {index + 1}:")
        print(f"Index 1: {image1}")
        print(f"Index 2: {image2}")
        print()  # Add a newline for better readability
else:
    print("No duplicate images found.")


Duplicate Images:
Duplicate pair 1:
Index 1: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170706 - Copy - Copy - Copy (Custom).jpg
Index 2: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170706 (Custom).jpg

Duplicate pair 2:
Index 1: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170708 - Copy - Copy - Copy (Custom).jpg
Index 2: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170708 (Custom).jpg

Duplicate pair 3:
Index 1: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170709 - Copy - Copy - Copy (Custom).jpg
Index 2: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170709 (Custom).jpg

Duplicate pair 4:
Index 1: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170712 - Copy - Copy - Copy (Custom).jpg
Index 2: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170712 (Custom).jpg

Duplicate pair 5:
Index 1: C:\Users\rawat\Downloads\MangoLeafB

In [3]:
import os
import hashlib
from collections import defaultdict

def get_file_hash(filename):
    # Create a hash of the file's content
    hasher = hashlib.md5()
    with open(filename, "rb") as f:
        while True:
            data = f.read(65536)  # Read in 64k chunks
            if not data:
                break
            hasher.update(data)
    return hasher.hexdigest()

def find_duplicate_images(directory):
    # Create a dictionary to store image hashes and their corresponding file paths
    hash_dict = defaultdict(list)

    for root, _, files in os.walk(directory):
        for file in files:
            # Check if the file is an image (you can add more image extensions as needed)
            if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                file_path = os.path.join(root, file)
                file_hash = get_file_hash(file_path)

                # Add the current file to the list of files with the same hash
                hash_dict[file_hash].append(file_path)

    # Filter out groups with only one image (not duplicates)
    duplicate_groups = {k: v for k, v in hash_dict.items() if len(v) > 1}
    
    return duplicate_groups

# Specify the directory containing your image dataset
image_directory = "C:\\Users\\rawat\\Downloads\\MangoLeafBD Dataset"

duplicate_groups = find_duplicate_images(image_directory)

if duplicate_groups:
    print("Duplicate Images:")
    for group_id, file_paths in enumerate(duplicate_groups.values(), 1):
        print(f"Duplicate group {group_id}:")
        for index, image_path in enumerate(file_paths, 1):
            print(f"Index {index}: {image_path}")
        print()  # Add a newline for better readability
else:
    print("No duplicate images found.")

Duplicate Images:
Duplicate group 1:
Index 1: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170706 (Custom).jpg
Index 2: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170706 - Copy - Copy - Copy (Custom).jpg

Duplicate group 2:
Index 1: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170708 (Custom).jpg
Index 2: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170708 - Copy - Copy - Copy (Custom).jpg

Duplicate group 3:
Index 1: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170709 (Custom).jpg
Index 2: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170709 - Copy - Copy - Copy (Custom).jpg

Duplicate group 4:
Index 1: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170712 (Custom).jpg
Index 2: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170712 - Copy - Copy - Copy (Custom).jpg

Duplicate group 5:
Index 1: C:\Users\rawat\Downloads\Mango

In [4]:
import os
import hashlib
from collections import defaultdict

def get_file_hash(filename):
    # Create a hash of the file's content
    hasher = hashlib.md5()
    with open(filename, "rb") as f:
        while True:
            data = f.read(65536)  # Read in 64k chunks
            if not data:
                break
            hasher.update(data)
    return hasher.hexdigest()

def find_duplicate_images(directory):
    # Create a dictionary to store image hashes and their corresponding file paths
    hash_dict = defaultdict(list)

    for root, _, files in os.walk(directory):
        for file in files:
            # Check if the file is an image (you can add more image extensions as needed)
            if file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                file_path = os.path.join(root, file)
                file_hash = get_file_hash(file_path)

                # Add the current file to the list of files with the same hash
                hash_dict[file_hash].append(file_path)

    # Filter out groups with only one image (not duplicates)
    duplicate_groups = {k: v for k, v in hash_dict.items() if len(v) > 1}
    
    return duplicate_groups

def remove_duplicate_images(duplicate_groups):
    for group_id, file_paths in enumerate(duplicate_groups.values(), 1):
        # Keep the first image in the group, delete the rest
        for index, image_path in enumerate(file_paths[1:], 1):
            if os.path.exists(image_path):
                os.remove(image_path)
                print(f"Removed duplicate image {index} in group {group_id}: {image_path}")
            else:
                print(f"Image {index} in group {group_id} does not exist: {image_path}")

# Specify the directory containing your image dataset
image_directory = "C:\\Users\\rawat\\Downloads\\MangoLeafBD Dataset"

duplicate_groups = find_duplicate_images(image_directory)

if duplicate_groups:
    print("Duplicate Images:")
    remove_duplicate_images(duplicate_groups)
else:
    print("No duplicate images found.")


Duplicate Images:
Removed duplicate image 1 in group 1: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170706 - Copy - Copy - Copy (Custom).jpg
Removed duplicate image 1 in group 2: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170708 - Copy - Copy - Copy (Custom).jpg
Removed duplicate image 1 in group 3: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170709 - Copy - Copy - Copy (Custom).jpg
Removed duplicate image 1 in group 4: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170712 - Copy - Copy - Copy (Custom).jpg
Removed duplicate image 1 in group 5: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170714 - Copy - Copy - Copy (Custom).jpg
Removed duplicate image 1 in group 6: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_170717 - Copy - Copy - Copy (Custom).jpg
Removed duplicate image 1 in group 7: C:\Users\rawat\Downloads\MangoLeafBD Dataset\Anthracnose\20211011_171141 -

In [1]:
from PIL import Image
import os

main_folder_path = "C:\\Users\\rawat\\Downloads\\MangoLeafBD Dataset"

# Create lists to store the loaded images and their labels
image_list = []
labels = []

# Iterate through subfolders (disease categories)
for subfolder in os.listdir(main_folder_path):
    subfolder_path = os.path.join(main_folder_path, subfolder)
    
    # Check if 'subfolder' is a directory
    if os.path.isdir(subfolder_path):
        label = subfolder
        
        # Iterate through the files in the subfolder
        for filename in os.listdir(subfolder_path):
            if filename.endswith('.jpg'):  # Adjust file extensions as needed
                image_path = os.path.join(subfolder_path, filename)
                
                # Open and load the image
                img = Image.open(image_path)
                
                # Append the loaded image to the list
                image_list.append(img)
                # Append the label to the labels list
                labels.append(label)

In [2]:
len(image_list)

3979

In [5]:
import numpy as np
print("Minimum pixel value:", np.min(image_list[0]))
print("Maximum pixel value:", np.max(image_list[0]))

Minimum pixel value: 0
Maximum pixel value: 227


In [6]:
target_width = 224
target_height = 224

resized_images = []

for img in image_list:
    # Resize the image to the target dimensions
    img = img.resize((target_width, target_height))

    resized_images.append(img)

In [7]:
import numpy as np

# Create a list to store the resized and normalized images
resized_and_normalized_images = []

for img in resized_images:

    img_array = np.array(img)

    # Normalize pixel values
    normalized_img = img_array / 227.0

    resized_and_normalized_images.append(normalized_img)

In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoded = label_encoder.fit_transform(labels)
print(label_encoded)

[0 0 0 ... 7 7 7]


In [9]:
print(np.array(resized_and_normalized_images).shape)
print(np.array(label_encoded).shape)

(3979, 224, 224, 3)
(3979,)


In [16]:
import pandas as pd
label_count=pd.DataFrame(labels).value_counts()
label_count

Bacterial Canker    500
Cutting Weevil      500
Gall Midge          500
Healthy             500
Powdery Mildew      500
Sooty Mould         500
Die Back            493
Anthracnose         486
dtype: int64

In [34]:
print("Shape of an example image:", resized_and_normalized_images[0].shape)
print("Minimum pixel value:", np.min(resized_and_normalized_images[0]))
print("Maximum pixel value:", np.max(resized_and_normalized_images[0]))

Shape of an example image: (224, 224, 3)
Minimum pixel value: 0.0
Maximum pixel value: 1.0


In [26]:
print(resized_and_normalized_images[10])
print(label_encoded[10])

[[[0.7092511  0.82378855 0.9339207 ]
  [0.7092511  0.82378855 0.9339207 ]
  [0.70484581 0.81938326 0.92951542]
  ...
  [0.69162996 0.77973568 0.89867841]
  [0.70484581 0.77973568 0.9030837 ]
  [0.7092511  0.7753304  0.9030837 ]]

 [[0.7092511  0.82378855 0.9339207 ]
  [0.7092511  0.82378855 0.9339207 ]
  [0.7092511  0.82378855 0.9339207 ]
  ...
  [0.69162996 0.77973568 0.89867841]
  [0.69603524 0.78854626 0.90748899]
  [0.69162996 0.78414097 0.9030837 ]]

 [[0.7092511  0.82378855 0.9339207 ]
  [0.7092511  0.82378855 0.9339207 ]
  [0.71365639 0.82819383 0.93832599]
  ...
  [0.68281938 0.78854626 0.9030837 ]
  [0.68722467 0.80176211 0.91189427]
  [0.6784141  0.79735683 0.90748899]]

 ...

 [[0.83700441 0.92951542 1.02202643]
  [0.83700441 0.92951542 1.02202643]
  [0.83700441 0.92951542 1.02202643]
  ...
  [0.80176211 0.88546256 0.96035242]
  [0.80176211 0.88546256 0.96035242]
  [0.80176211 0.88546256 0.96035242]]

 [[0.83700441 0.92951542 1.02202643]
  [0.83700441 0.92951542 1.02202643]


In [41]:
import random

selected_images = []
selected_labels = []

# Create a dictionary to organize images by class
class_images = {class_name: [] for class_name in set(label_encoded)}

# Populate the dictionary with images and their corresponding labels
for image, label in zip(image_list, label_encoded):
    class_images[label].append(image)

desired_per_class = 400

# Loop through each class and select the desired number of images
for class_name, image_list in class_images.items():
    if len(image_list) >= desired_per_class:
        selected_images.extend(random.sample(image_list, desired_per_class))
        selected_labels.extend([class_name] * desired_per_class)
    else:

        selected_images.extend(image_list)
        selected_labels.extend([class_name] * len(image_list))